### USUÁRIOS

### Listar todos os usuários
GET http://localhost:3000/users

### Criar usuário
POST http://localhost:3000/users
content-type: application/json

{
  "nome": "Henrique Alves",
  "telefone": "11999999999",
  "email": "henrique@email.com",
  "senha": "senha123"
}

### Autenticar usuário
POST http://localhost:3000/users/authenticate
content-type: application/json

{
  "email": "henrique@email.com",
  "senha": "123456"
}

###

### Solicitações

### Listar todos as Solicitações
GET http://localhost:3000/solicitacoes

### Criar Solicitação
POST http://localhost:3000/solicitacoes
content-type: application/json

{
  "nome_medicamento": "Paracetamol",
  "enfermeiro_responsavel": "Ana Silva",
  "quantidade": 20,
  "dataSolicitacao": "2024-06-15T10:00:00Z"
}

###

### Medicamentos

### Listar todos os Medicamentos
GET http://localhost:3000/medicamentos

### Criar Medicamento
POST http://localhost:3000/medicamentos
content-type: application/json

{
  "nome": "Ibuprofeno",
  "dosagem": "400mg",
  "forma_administrativa": "Comprimido",
  "dataFab": "2023-01-01",
  "dataVal": "2025-01-01",
  "lote": "AB1234",
  "no_estoque": 100,
  "complemento": "alergia a penicilina",
  "categoria": "Analgésico"

}

###

### Buscar categoria (retorna lista)
GET http://localhost:3000/users/buscar?categoria